services:
  # Defining what image to build the container from
  fast-api:
    image: rest_api:latest
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    container_name: fast_api
    volumes:
      - ./rest_api_test_framework:/rest_api_test_framework
    env_file:
      - secrets.env
    stdin_open: true
    tty: true
    command: /bin/bash

